export default {
  /* AWS account */
  AWS_RESERVES_ACCOUNT_SELECTION: 'AWS_RESERVES_ACCOUNT_SELECTION',

  /* Dates */
  AWS_RESERVES_SET_DATES: 'AWS_RESERVES_SET_DATES',
  AWS_RESERVES_RESET_DATES: 'AWS_RESERVES_RESET_DATES',
  AWS_RESERVES_CLEAR_DATES: 'AWS_RESERVES_CLEAR_DATES',


	/* Reserved */
	AWS_RESERVES_GET_RESERVED: 'AWS_RESERVES_GET_RESERVED',
	AWS_RESERVES_GET_RESERVED_SUCCESS: 'AWS_RESERVES_GET_RESERVED_SUCCESS',

  AWS_RESERVES_GET_RESERVED_ERROR: 'AWS_RESERVES_GET_RESERVED_ERROR',
  AWS_RESERVES_GET_RESERVED_CLEAR: 'AWS_RESERVES_GET_RESERVED_CLEAR',

	/* Usage */
	AWS_RESERVES_GET_USAGE: 'AWS_RESERVES_GET_USAGE',
	AWS_RESERVES_GET_USAGE_SUCCESS: 'AWS_RESERVES_GET_USAGE_SUCCESS',

  AWS_RESERVES_GET_USAGE_ERROR: 'AWS_RESERVES_GET_USAGE_ERROR',
  AWS_RESERVES_GET_USAGE_CLEAR: 'AWS_RESERVES_GET_USAGE_CLEAR',

	/* Discount */
	AWS_RESERVES_GET_DISCOUNT: 'AWS_RESERVES_GET_DISCOUNT',
	AWS_RESERVES_GET_DISCOUNT_SUCCESS: 'AWS_RESERVES_GET_DISCOUNT_SUCCESS',

  AWS_RESERVES_GET_DISCOUNT_ERROR: 'AWS_RESERVES_GET_DISCOUNT_ERROR',
  AWS_RESERVES_GET_DISCOUNT_CLEAR: 'AWS_RESERVES_GET_DISCOUNT_CLEAR',
};
