export default {

  /* USAGES data */
  AWS_GET_USAGES_DATA: 'AWS_GET_USAGES_DATA',
  AWS_GET_USAGES_DATA_SUCCESS: 'AWS_GET_USAGES_DATA_SUCCESS',
  AWS_GET_USAGES_DATA_ERROR: 'AWS_GET_USAGES_DATA_ERROR',
  AWS_GET_USAGES_DATA_CLEAR: 'AWS_GET_USAGES_DATA_CLEAR',

  /* Dates */
  AWS_SET_USAGES_DATES: 'AWS_SET_USAGES_DATES',
  AWS_CLEAR_USAGES_DATES: 'AWS_CLEAR_USAGES_DATES',
};
